// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MarketPrice } from "./MarketPrice";

export interface ChestInfo { name: string, market_hash_name: string, icon_url: string, amount: number, price: MarketPrice, }