// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface FullAsset { name: string, appid: number, assetid: number, classid: number, instanceid: number, amount: number, icon_url: string, market_hash_name: string, }