// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MarketPrice { success: boolean, median_price: number, volume: number, lowest_price: number, }