// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PriceHistoryResponse { success: boolean, price_prefix: string, price_suffix: string, prices: Array<[string, number, string]>, }